myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index),   # localhost:8000/myapp/
    path('products/', views.products, name='products'), # localhost:8000/myapp/products/
    # path('products/', views.ProductListView.as_view(), name='products'), # We used Class list view
    # path('products/<int:id>/', views.product_details, name='product_details'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_details'), # class based detail view
    path('products/add/', views.add_product, name='add_product'),
    # path('products/add/', views.ProductCreateView.as_view(), name='add_product'), # Class based create view
    path('products/update/<int:id>/', views.update_product, name='update_product'),
    # path('products/update/<int:pk>/', views.ProductUpdateView.as_view(), name='update_product'), # Class based Update view
    path('products/delete/<int:id>/', views.delete_product, name='delete_product'),
    # path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete_product'), # Class based Delete view
    path('products/mylistings/', views.my_listings, name='my_listings'),
    path('success/', views.PaymentSuccessView.as_view(), name='success'), # Class based Success view
    path('failed/', views.PaymentFailedView.as_view(), name='failed'),
    path('api/checkout-session/<id>',views.create_checkout_session,name='api_checkout_session'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), # localhost:8000/admin/
    path('myapp/', include('myapp.urls')), # localhost:8000/myapp/
    path('users/', include('users.urls')), # localhost:8000/usrs/
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_view

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),   # localhost:8000/users/register
    path('login/', authentication_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('createprofile/', views.create_profile, name='createprofile'),
    path('sellerprofile/<int:id>/', views.seller_profile, name='sellerprofile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pictures')
    contact_number = models.CharField(default='1111111111', max_length=30)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'focus:outline-none',
                                                                            'placeholder': 'example@gmail.com' }))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'focus:outline-none',
                                                                            'placeholder': 'Your name please' }))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none',
                                                                            'placeholder': 'Make a strong password' }))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none',
                                                                            'placeholder': 'Type password again' }))

    # This is built in user model > collection or table
    class Meta:
        model=User
        fields = ('email', 'username', 'password1', 'password2')

    # Now we need to save the user
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('/myapp/products/') # redirect to a path not template

    form = NewUserForm()
    context = {
        'form':form
    }
    return render(request, 'users/register.html', context=context)

@login_required
def profile(request):
    return render(request, 'users/profile.html')

@login_required
def create_profile(request):
    if request.method == 'POST':
        image = request.FILES['upload']
        contact_number = request.POST.get('contact_number')
        user = request.user
        # Add data to databse
        profile = Profile(image=image, contact_number=contact_number, user=user)
        profile.save()
        return redirect('/users/profile/')
    return render(request, 'users/createprofile.html')

def seller_profile(request, id):
    seller = User.objects.get(id=id)
    context = {
        'seller':seller
    }
    return render(request, 'users/sellerprofile.html', context=context)

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="">Upload Your Profile Image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload" placeholder="Please upload a profile image">
    </div>
    <div class="mb-4">
        <label for="">Contact Number</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="contact_number" id="contact_number" placeholder="+3600000000">
    </div>
    <button class="inline-block px-6 py-2 border-2 border-purple-600 text-purple-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out" type="submit"> Confirm </button>
</form>

{% endblock body %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block body %}

<h1 class="text-2xl m-10 font-bold">Log In</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-lg m-10 rounded px-8 pt-6 pb-8 mb-4" method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.username}}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password}}
            </div>
        </div>
        <button class="mt-2 inline-block px-6 py-2 border-2 border-green-500 text-green-500 font-medium text-xs leading-tight uppercase rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out" type="submit"> Log in </button>
    </form>
    <div class="m-10">Do not have an account? <a class="text-blue-500" href="{% url 'users:register' %}">Register Now!</a></div>
</div>

{% endblock body %}

users/templates/users/logout.html
{% extends 'myapp/base.html' %}
{% block body %}

<h1 class="text-2xl m-10 font-bold">You have been logged out successfully</h1>

{% endblock body %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{% block body %}

<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div class="h-40 w-20 rounded-md">
            <img src="{{user.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            Welcome {{ user.username }}
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            Contact Number: {{ user.profile.contact_number }}
        </div>
        <div class="mb-2 px-6 py-4"">
            <a type="button" href="{% url 'users:createprofile' %}" class="inline-block px-6 py-2 border-2 border-purple-600 text-purple-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">Edit Profile</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block body %}

<h1 class="text-2xl m-10 font-bold">New User Registration</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-lg m-10 rounded px-8 pt-6 pb-8 mb-4" method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.username}}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Email</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.email}}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password1}}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Confirm Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password2}}
            </div>
        </div>
        <button class="mt-2 inline-block px-6 py-2 border-2 border-green-500 text-green-500 font-medium text-xs leading-tight uppercase rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out" type="submit"> Submit to register </button>
    </form>
    <div class="m-10">Already have an account? <a class="text-blue-500" href="{% url 'users:login' %}">Login Now!</a></div>
</div>

{% endblock body %}

users/templates/users/sellerprofile.html
{% extends 'myapp/base.html' %}
{% block body %}

<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div class="h-40 w-20 rounded-md">
            <img src="{{seller.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            Welcome {{ seller.username }}
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            Contact Number: {{ seller.profile.contact_number }}
        </div>
    </div>
</div>

{% endblock %}