myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index),   # localhost:8000/myapp/
    path('products/', views.products, name='products'), # localhost:8000/myapp/products/
    # path('products/', views.ProductListView.as_view(), name='products'), # We used Class list view
    # path('products/<int:id>/', views.product_details, name='product_details'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_details'), # class based detail view
    path('products/add/', views.add_product, name='add_product'),
    # path('products/add/', views.ProductCreateView.as_view(), name='add_product'), # Class based create view
    path('products/update/<int:id>/', views.update_product, name='update_product'),
    # path('products/update/<int:pk>/', views.ProductUpdateView.as_view(), name='update_product'), # Class based Update view
    path('products/delete/<int:id>/', views.delete_product, name='delete_product'),
    # path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete_product'), # Class based Delete view
    path('products/mylistings/', views.my_listings, name='my_listings'),
    path('success/', views.PaymentSuccessView.as_view(), name='success'), # Class based Success view
    path('failed/', views.PaymentFailedView.as_view(), name='failed'),
    path('api/checkout-session/<id>',views.create_checkout_session,name='api_checkout_session'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), # localhost:8000/admin/
    path('myapp/', include('myapp.urls')), # localhost:8000/myapp/
    path('users/', include('users.urls')), # localhost:8000/usrs/
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_view

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),   # localhost:8000/users/register
    path('login/', authentication_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('createprofile/', views.create_profile, name='createprofile'),
    path('sellerprofile/<int:id>/', views.seller_profile, name='sellerprofile'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
# This is a product model
class Products(models.Model): # It's better to define class name not plural
    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):  # Canonical URL
        return reverse('myapp:products')
    
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    seller_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=300)
    image = models.ImageField(blank=True, upload_to='images')

class OrderDetail(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(to='Products', on_delete=models.PROTECT)
    amount = models.IntegerField()
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Products, OrderDetail
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator

from django.http.response import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
import stripe


# Create your views here.
def index(request):
    return HttpResponse('<h1>Hellllo Pejman :)</h1>')

# Function based view
def products(request):
    if request.method == 'POST':
        page_obj = searched_item = request.POST['search']
        if searched_item != "" and searched_item is not None:
            page_obj = Products.objects.filter(name__contains=searched_item)
        #Pagination
        per_page = request.GET.get("per_page", 3)
        paginator = Paginator(page_obj, per_page)
        page_number = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj':page_obj
        }
        return render(request, 'myapp/index.html', context=context)
        
    products = Products.objects.get_queryset().order_by('name')
    #Pagination
    per_page = request.GET.get("per_page", 3)
    paginator = Paginator(products, per_page)
    page_number = request.GET.get("page", 1)
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj':page_obj
    }
    return render(request, 'myapp/index.html', context=context)

# Class based view for above products view [ListView]
class ProductListView(ListView):
    model = Products
    template_name = 'myapp/index.html'
    context_object_name = 'products'
    paginate_by = 3

def product_details(request, id):
    product = Products.objects.get(id=id)
    context = {
        'product': product
    }
    return render(request, 'myapp/details.html', context=context)

# Class based view for above product detail view [DetailView]
class ProductDetailView(DetailView):
    model = Products
    template_name = 'myapp/details.html'
    context_object_name = 'product'
    pk_url_kwarg = 'pk'

    def get_context_data(self,**kwargs):
        context = super(ProductDetailView,self).get_context_data(**kwargs)
        context['stripe_publishable_key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


@login_required
def add_product(request):
    if request.method == 'POST':
        # Get data from form
        seller_name = request.user
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        image = request.FILES['upload']
        # Add data to databse
        product = Products(name=name, price=price, description=description, image=image, seller_name=seller_name)
        product.save()
        return redirect('/myapp/products/') # redirect to url not template
    return render(request, 'myapp/addproduct.html')

# Class based view for creating product
@login_required
class ProductCreateView(CreateView):
    model = Products
    fields = ['name', 'price', 'description', 'image', 'seller_name']
    # Now we need to create template for it, the name come from model name >> products_form.html


@login_required
def update_product(request, id):
    product = Products.objects.get(id=id)
    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.description = request.POST.get('description')
        product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products/') # redirect to url not template name
    context = {
        'product':product
    }
    return render(request, 'myapp/updateproduct.html', context=context)

# Class based view for Update a product
@login_required
class ProductUpdateView(UpdateView):
    model = Products
    fields = ['name', 'price', 'description', 'image', 'seller_name']
    template_name_suffix = '_update_form' # then just make product_update_form.html

@login_required
def delete_product(request, id):
    product = Products.objects.get(id=id)
    context = {
        'product':product
    }
    
    if request.method == 'POST':
        product.delete()
        return redirect('/myapp/products/')
    return render(request, 'myapp/delete.html', context=context)

# Class based view for Delete a product
@login_required
class ProductDeleteView(DeleteView):
    model = Products # then just create a template products_confirm_delete.html
    success_url = reverse_lazy('myapp:products')

def my_listings(request):
    products = Products.objects.filter(seller_name=request.user)
    context = {
        'products': products
    }
    return render(request, 'myapp/my_listings.html', context=context)


@csrf_exempt
def create_checkout_session(request,id):
    product = get_object_or_404(Products,pk=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        customer_email = request.user.email,
        
        payment_method_types=['card'],
        line_items=[
            {
                'price_data':{
                    'currency':'usd',
                    'product_data':{
                        'name':product.name,
                    },
                    'unit_amount':int(product.price *100),
                },
                'quantity':1,
            }
        ],
        mode='payment',
        success_url = request.build_absolute_uri(reverse('myapp:success'))+"?session_id={CHECKOUT_SESSION_ID}",
        cancel_url= request.build_absolute_uri(
            reverse('myapp:failed')),
    )
    
    order = OrderDetail()
    order.customer_username = request.user.username
    order.product = product
    order.stripe_payment_intent = checkout_session['payment_intent']
    order.amount = int(product.price*100)
    order.save()
    return JsonResponse({'sessionId':checkout_session.id})

class PaymentSuccessView(TemplateView):
    template_name ='myapp/payment_success.html'
    
    def get(self,request,*args,**kwargs):
        session_id = request.GET.get('session_id')
        if session_id is None:
            return HttpResponseNotFound()
        session = stripe.checkout.Session.retrieve(session_id)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        order = get_object_or_404(OrderDetail,stripe_payment_intent=session.payment_intent)
        order.has_paid = True
        order.save()
        return render(request,self.template_name)
    
class PaymentFailedView(TemplateView):
    template_name = 'myapp/payment_failed.html'

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block body %}

<h1 class="text-2xl font-bold m-10"> + Please add a new product here!</h1>
<form class="w-2/5 bg-white shadow-lg m-10 px-10 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Product Name</label>
        <input class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700" type="text" name="name" id="name" placeholder="For example: iPhone" autocomplete="off">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Product's Price</label>
        <input class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700" type="text" name="price" id="price" placeholder="For example: 1000" autocomplete="off">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="description">Description</label>
        <input class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700" type="text" name="description" id="description" placeholder="For example: iPhone 14" autocomplete="off">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Image of product</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <input class="text-center inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out" type="submit" value="Add Product" name="Add Product" id="">
</form>

{% endblock body %}

myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tech & Sell</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    <nav class="bg-black shadow-2xl">
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between">
                <div class="flex space-x-7">
                    <div>
                        <a class="flex px-2 py-4 items-center" href="">
                            <img class="h-8 w-8" src="{% static 'myapp/images/icon2.png' %}" alt="Logo Not Found!">
                            <span class="text-white text-lg font-semibold">Tech & Sell</span>
                        </a>
                    </div>
                    <div class="flex items-center space-x-1">
                        <a class="px-2 py-4 text-white font-semibold border-b-4 border-yellow-500" href="{% url 'myapp:products' %}">Home</a>
                        <a class="px-2 py-4 text-white font-semibold border-b-4 border-yellow-500" href="{% url 'myapp:add_product' %}">Add Product</a>

                        {% if user.is_authenticated %}
                        <a class="px-10 py-4 text-white font-semibold border-b-4 border-yellow-500" href="{% url 'myapp:my_listings' %}">My List</a>
                        <a class="px-10 py-4 text-white font-semibold border-b-4 border-red-500" href="{% url 'users:logout' %}">Logout</a>
                        <a class="px-10 py-4 text-white font-semibold border-b-4 border-green-500" href="{% url 'users:profile' %}">My Profile</a>
                        {% else %}
                        <a class="px-20 py-4 text-white font-semibold border-b-4 border-green-500" href="{% url 'users:login' %}">Login</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </nav>
    
    {% block body %}

    {% endblock body %}

</body>
</html>

myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}
{% block body %}

<h1 class="text-2xl m-10 font-bold">Delete Product</h1>
<form class="bg-white shadow-lg m-10 w-2/5 rounded px-8 pt-6 pb-8 mb-4" method="POST">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">Are you sure to delete this product item?</label><br>
        <label class="block text-gray-700 text-sm font-bold mb-2" style="color:red;">Warning: deleted item can not be restored</label>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">{{ product.name }}</label>
    </div>
    <div class="mb-4"> 
        <img class="h-21 w-21" src="{{ product.image.url }}" alt="">
    </div>
    <input class="button bg-red-500 text-white px-5 py-3 uppercase rounded-full shadow-md" type="submit" name="confirm" id="confirm" value="Delete Product">
    <a class="button bg-green-500 text-white px-5 py-3 uppercase rounded-full shadow-md" href="{% url 'myapp:products' %}">Cancel</a>
</form>

{% endblock body %}

myapp/templates/myapp/details.html
{% extends 'myapp/base.html' %}
{% block body %}
    
    <div class="flex p-10 w-full h-200">
        <img class="w-1/3" src="{{ product.image.url }}" alt="">
        <div class="w-2/3 text-xl ml-10 mt-5">
            <div class="mt-5">{{ product.name }}</div>
            <div class="mt-5 text-blue-500">€ {{ product.price }}</div>
            <div class="mt-5 text-gray-500">Posted by: 
                <a href="{% url 'users:sellerprofile' product.seller_name.id %}">{{ product.seller_name }}</a>
            </div>
            <!-- <div class="mt-5 text-gray-500">Seller contact number: {{ user.profile.contact_number }}</div> -->
            <div class="mt-5 text-gray-500">Seller contact number: {{ product.seller_name.profile.contact_number }}</div>
            <div class="mt-5 text-gray-400">{{ product.description }}</div>
            <div>
                <!-- <button class="text-white bg-green-500 rounded-full px-3 py-2 mt-8" id="checkout">
                    Checkout
                </button> -->

                <!--Canonical  href="{{ product.get_absolute_url }}"-->
                <!-- <a href="{{ product.get_absolute_url }}">Canonical</a> -->
            </div>
        </div>
    </div>
    <!-- <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">

        var stripe = Stripe('{{ stripe_publishable_key }}')
        var checkoutButton = document.getElementById('checkout')
        checkoutButton.addEventListener('click',function(){
            fetch("{% url 'myapp:api_checkout_session' id=product.id %}",{method:'POST',})
            .then(function(response){
                return response.json()
            })
            .then(function(session){
                return stripe.redirectToCheckout({sessionId:session.sessionId})
            })
            .then(function(result){
                if(result.error){
                    alert(result.error.message)
                }
            })
            .catch(function(error){
                console.error('Error', error)
            })
        })
    </script> -->
{% endblock %}

myapp/templates/myapp/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tech & Sell</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    <nav class="bg-black shadow-2xl">
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between">
                <div class="flex space-x-7">
                    <div>
                        <a class="flex px-2 py-4 items-center" href="">
                            <img class="h-8 w-8" src="{% static 'myapp/images/icon2.png' %}" alt="Logo Not Found!">
                            <span class="text-white text-lg font-semibold">Tech & Sell</span>
                        </a>
                    </div>
                    <div class="flex items-center space-x-1">
                        <a class="px-2 py-4 text-white font-semibold border-b-4 border-yellow-500" href="{% url 'myapp:products' %}">Home</a> 
                        <a class="px-2 py-4 text-white font-semibold border-b-4 border-yellow-500" href="{% url 'myapp:add_product' %}">Add Product</a>

                        {% if user.is_authenticated %}
                        <a class="px-10 py-4 text-white font-semibold border-b-4 border-yellow-500" href="{% url 'myapp:my_listings' %}">My List</a>
                        <a class="px-10 py-4 text-white font-semibold border-b-4 border-red-500" href="{% url 'users:logout' %}">Logout</a>
                        <a class="px-10 py-4 text-white font-semibold border-b-4 border-green-500" href="{% url 'users:profile' %}">My Profile</a>
                        {% else %}
                        <a class="px-20 py-4 text-white font-semibold border-b-4 border-green-500" href="{% url 'users:login' %}">Login</a>
                        {% endif %}

                    </div>
                    <!--Search field-->
                    <form method="POST">
                        {% csrf_token %}
                        <div class="relative mx-auto text-gray-600 lg:block hidden items-center">
                            <input
                                class="mt-7 border-2 border-gray-300 bg-white h-8 pl-2 pr-8 rounded-lg text-sm focus:outline-none items-center"
                                type="search" name="search" placeholder="Search">
                            <button type="submit" class="absolute right-0 top-0 mt-9 mr-2">
                                <svg class="text-gray-600 h-4 w-4 fill-current" xmlns=""
                                     version="1.1" id="Capa_1" x="0px" y="0px"
                                     viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;"
                                     xml:space="preserve"
                                     width="512px" height="512px">
                            <path
                                d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
                          </svg>
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </nav>


    <!-- Site hero starts here -->
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
            <h1 class="text-4xl font-extrabold text-gray-900 md:text-6xl sm:text-5xl">
                <span class="block xl:inline">The website prices are not real.</span>
                <span class="block text-blue-500 xl:inline">Just for educational goals</span>
            </h1>
            <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:max-auto md:mt-4 md:text-xl lg:mx-0">
                The website just try to test django authentication, payment gate ... :)
            </p>
        </div>
    </main>
    <!-- Site here ends here-->

    <div class="flex mt-5 p-10 justify-center">
        <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Available products</h2>
    </div>

    <!-- This section is related to products name, price, des and image -->
    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
        <!-- Card -->
        {% for product in page_obj %}

        <a href="{% url 'myapp:product_details' product.id %}"> 
            <div class="rounded overflow-hidden shadow-lg">
                <img class="w-full" src="{{ product.image.url }}" alt="">
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">
                        {{ product.name }}
                    </div>
                    <div class="font-bold text-xl text-blue-500 mb-2">
                        € {{ product.price }} 
                    </div>
                    <div class="font-bold mb-2">
                        Posted by: <span class="text-indigo-500">{{ product.seller_name }} </span> 
                    </div>
                    <p class="text-base text-gray-700">
                        {{ product.description }}
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    <!-- Product section end -->

    <!-- Pagination code starts here -->
    <div class="pagination flex justify-center items-center mb-3">
        <span>
            {% if page_obj.has_previous %}
                <a href="?page=1" class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-blue-500 border-blue-500 z10">First</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-blue-500 border-blue-500 z10">Previous</a>
            {% endif %}
            <span class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-blue-500 border-blue-500 z10">
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-blue-500 border-blue-500 z10">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-blue-500 border-blue-500 z10">Last</a>
            {% endif %}
        </span>
    </div>
    <!-- Pagination code end here -->

</body>
</html>

myapp/templates/myapp/my_listings.html
{% extends 'myapp/base.html' %}
{% block body %}

<div class="text-2xl m-10 p-10 font-bold">My Products List</div>
{% for product in products %}
    <div class="itemcontainer flex shadow-lg m-10 p-10">
        <span class="w-1/5">
            <img class="w-40 h-40" src="{{ product.image.url }}" alt="">
        </span>
        <span class="w-2/5">
            <div class="font-bold text-gray-700">{{ product.name }}</div>
            <div class="text-green-500">€ {{ product.price }}</div>
            <div>{{ product.description }}</div>
        </span>
        <span class="w-1/5 m-10 mx-10">
            <a class="bg-blue-500 text-white font-bold px-5 py-2 rounded-full" href="{% url 'myapp:update_product' product.id %}">Update</a>
        </span>
        <span class="w-1/5 m-10 mx-10">
            <a class="bg-red-500 text-white font-bold px-5 py-2 rounded-full" href="{% url 'myapp:delete_product' product.id %}">Delete</a>
        </span>
    </div>
{% endfor %}

{% endblock body %}

myapp/templates/myapp/payment_failed.html
{% extends 'myapp/base.html' %}
{% block body %}

<div>
    <h1 class="text-2xl m-10 font-bold">
        Payment Failed. Please try again!
    </h1>
</div>

{% endblock body%}

myapp/templates/myapp/payment_success.html
{% extends 'myapp/base.html' %}
{% block body %}

<div>
    <h1 class="text-2xl m-10 font-bold">
        The order has been submitted, the payment was successful.
    </h1>
</div>

{% endblock body%}

myapp/templates/myapp/products_confirm_delete.html
<form method="POST">
    {% csrf_token %}
    <p>Are you sure to delete "{{ object }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>

myapp/templates/myapp/products_form.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block body %}

<h1 class="text-2xl font-bold m-10"> + Please add a new product here!</h1>
<form class="w-2/5 bg-white shadow-lg m-10 px-10 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Product Name</label>
        <div class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700">
            {{form.name}}
        </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Product's Price</label>
        <div class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700">
            {{form.price}}
        </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="description">Description</label>
        <div class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700">
            {{form.description}}
        </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Image of product</label>
        <div class="py-2">
            {{form.image}}
        </div>
    </div>
    <div class="hidden mb-4">
        {{form.seller_name}}
    </div>
    <input class="text-center inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out" type="submit" value="Add Product" name="Add Product" id="">
</form>

{% endblock body %}

myapp/templates/myapp/products_update_form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Update" id="Update">
</form>

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block body %}

<h1 class="text-2xl font-bold m-10"> Update product data here!</h1>
<form class="w-2/5 bg-white shadow-lg m-10 px-10 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Product Name</label>
        <input class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700" value="{{ product.name }}" type="text" name="name" id="name" placeholder="For example: iPhone" autocomplete="off">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Product's Price</label>
        <input class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700" value="{{ product.price }}" type="text" name="price" id="price" placeholder="For example: 1000" autocomplete="off">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="description">Description</label>
        <input class="shadow appearance-none border rounded mr-10 px-3 py-2 text-gray-700" value="{{ product.description }}" type="text" name="description" id="description" placeholder="For example: iPhone 14" autocomplete="off">
    </div>
    <div class="mb-4">
        <img class="w-20 h-20" src="{{ product.image.url }}" alt="Image Not Found!">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Image of product</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <input class="text-center inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out" type="submit" value="Update Product" name="Update Product" id="">
</form>

{% endblock body %}